# .github/workflows/build-tag-on-main.yml
name: Create Build Tag on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  create_build_tag:
    if: "!startsWith(github.event.head_commit.message, 'release:')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest stable version
        id: stable
        run: |
          git fetch --tags
          latest=$(git tag --sort=-v:refname | grep -E '^\d+\.\d+\.\d+$' | head -n 1)
          echo "LATEST_TAG=$latest" >> $GITHUB_ENV

      - name: Get next build number
        id: build
        run: |
          prefix=$LATEST_TAG
          git fetch --tags
          count=$(git tag --sort=-v:refname | grep -E "^$prefix-[0-9]+$" | wc -l)
          next=$((count + 1))
          echo "NEW_TAG=$prefix-$next" >> $GITHUB_ENV

      - name: Create and push new build tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
