name: Create Build Tag on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  create_build_tag:
    if: "!startsWith(github.event.head_commit.message, 'release:')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest stable version
        id: stable
        run: |
          git fetch --tags
          latest=$(git tag --sort=-v:refname | grep -E '^\d+\.\d+\.\d+$' | head -n 1)
          echo "LATEST_TAG=$latest" >> $GITHUB_ENV

      - name: Get next build number
        id: build
        run: |
          prefix=$LATEST_TAG
          git fetch --tags
          count=$(git tag --sort=-v:refname | grep -E "^$prefix-[0-9]+$" | wc -l)
          next=$((count + 1))
          echo "NEW_TAG=$prefix-$next" >> $GITHUB_ENV

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Create and push new build tag
        run: |
          echo "Creating and pushing tag: $NEW_TAG"
          
          # Configurar o token de autenticação para o git
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

          # Criar a tag
          git tag "$NEW_TAG"
          
          # Empurrar para o repositório remoto
          git push origin "$NEW_TAG"
