name: Create Build Tag on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  create_build_tag:
    if: "!startsWith(github.event.head_commit.message, 'release:')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ensure at least one stable tag exists
        id: check_or_create
        run: |
          git fetch --tags
          latest=$(git tag --sort=-v:refname | grep -E '^\d+\.\d+\.\d+$' | head -n 1 || true)

          if [ -z "$latest" ]; then
            # Verificar se a tag 1.0.0 já existe
            if git tag | grep -q "^1.0.0$"; then
              # Se a tag já existe localmente, empurrar para o remoto
              echo "Tag 1.0.0 already exists locally. Pushing to remote..."
              git push origin 1.0.0
            else
              # Criar e empurrar a tag 1.0.0 caso não exista
              echo "No stable tag found. Creating initial tag 1.0.0"
              git config user.name "github-actions"
              git config user.email "actions@github.com"
              git tag "1.0.0"
              git push origin "1.0.0"
            fi
            echo "CREATED_INITIAL_TAG=true" >> $GITHUB_ENV
            echo "LATEST_TAG=1.0.0" >> $GITHUB_ENV
          else
            echo "LATEST_TAG=$latest" >> $GITHUB_ENV
            echo "CREATED_INITIAL_TAG=false" >> $GITHUB_ENV
          fi

      - name: Skip if initial tag was just created
        if: env.CREATED_INITIAL_TAG == 'true'
        run: echo "Initial tag created. No build tag needed yet."

      - name: Get next build number
        if: env.CREATED_INITIAL_TAG != 'true'
        run: |
          prefix=$LATEST_TAG
          count=$(git tag --sort=-v:refname | grep -E "^$prefix-[0-9]+$" | wc -l)
          next=$((count + 1))
          echo "NEW_TAG=$prefix-$next" >> $GITHUB_ENV

      - name: Create and push new build tag
        if: env.CREATED_INITIAL_TAG != 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
