name: Create Build Tag on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  create_build_tag:
    if: "!startsWith(github.event.head_commit.message, 'release:')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ensure at least one stable tag exists
        id: check_or_create
        run: |
          git fetch --tags
          remote_tag=$(git ls-remote --tags origin 1.0.0 || true)
            
          if [ -z "$remote_tag" ]; then
            echo "No remote tag 1.0.0 found. Creating initial tag 1.0.0."
            git tag -a 1.0.0 -m "Initial tag 1.0.0"
            git push origin 1.0.0
            echo "CREATED_INITIAL_TAG=true" >> $GITHUB_ENV
          else
            echo "Remote tag 1.0.0 already exists."
            latest=$(git tag --sort=-v:refname | grep -E '^\d+\.\d+\.\d+$' | head -n 1 || true)
            echo "Latest stable tag: $latest"
            echo "LATEST_TAG=$latest" >> $GITHUB_ENV
          fi

      - name: Skip if initial tag was just created
        if: env.CREATED_INITIAL_TAG == 'true'
        run: echo "Initial tag created. Skipping build tag creation."

      - name: Get next build number
        if: env.CREATED_INITIAL_TAG != 'true'
        run: |
          prefix=$LATEST_TAG
          count=$(git tag --sort=-v:refname | grep -E "^$prefix-[0-9]+$" | wc -l)
          next=$((count + 1))
          echo "NEW_TAG=$prefix-$next" >> $GITHUB_ENV

      - name: Create and push new build tag
        if: env.CREATED_INITIAL_TAG != 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
