name: Manual Create Minor Version and Release Branch

on:
  workflow_dispatch:

jobs:
  create_minor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest stable version
        id: get_latest
        run: |
          git fetch --tags
          latest=$(git tag --sort=-v:refname | grep -E '^\d+\.\d+\.\d+$' | head -n 1)
          echo "LATEST_TAG=$latest" >> $GITHUB_ENV

      - name: Compute new minor version
        id: compute
        run: |
          major=$(echo "$LATEST_TAG" | cut -d. -f1)
          minor=$(echo "$LATEST_TAG" | cut -d. -f2)
          next_minor=$((minor + 1))
          new_version="$major.$next_minor.0"
          release_branch="release/$LATEST_TAG"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          echo "RELEASE_BRANCH=$release_branch" >> $GITHUB_ENV

      - name: Create new tag and release branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag "$NEW_VERSION"
          git push origin "$NEW_VERSION"
          git checkout -b "$RELEASE_BRANCH"
          git push origin "$RELEASE_BRANCH"
