name: Create Patch Tag on Release Merge

on:
  push:
    branches:
      - release/**

jobs:
  create_patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract release version
        id: extract
        run: |
          git fetch --tags
          base_branch="${GITHUB_REF#refs/heads/release/}"
          echo "RELEASE_BASE=$base_branch" >> $GITHUB_ENV

      - name: Get next patch version
        id: next_patch
        run: |
          major=$(echo "$RELEASE_BASE" | cut -d. -f1)
          minor=$(echo "$RELEASE_BASE" | cut -d. -f2)
          patch=$(echo "$RELEASE_BASE" | cut -d. -f3)
          current_prefix="$major.$minor"
          current_patch=$(git tag --sort=-v:refname | grep -E "^$current_prefix\.[0-9]+$" | tail -n 1 | cut -d. -f3)
          if [ -z "$current_patch" ]; then
            next_patch=$((patch + 1))
          else
            next_patch=$((current_patch + 1))
          fi
          new_tag="$major.$minor.$next_patch"
          echo "NEW_PATCH=$new_tag" >> $GITHUB_ENV

      - name: Create and push patch tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag "$NEW_PATCH"
          git push origin "$NEW_PATCH"
